[package]
name = "jsonrpsee-types"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Shared types for jsonrpsee"
edition = "2018"
license = "MIT"

[dependencies]
async-trait = "0.1"
async-std = "1"
log = "0.4"
futures = "0.3"
thiserror = "1.0"
tokio = "1"
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_json = "1.0"
smallvec = "1.0"
