[package]
name = "jsonrpsee-examples"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Examples for jsonrpsee"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1"
env_logger = "0.8"
futures = "^0.3.13"
log = "0.4"
jsonrpsee-types = { path = "../types", version = "0.1" }
jsonrpsee-client = { path = "../client", version = "0.1" }
jsonrpsee-ws-server = { path = "../ws-server", version = "0.1" }
jsonrpsee-http-server = { path = "../http-server", version = "0.1" }
jsonrpsee-test-utils = { path = "../test-utils", version = "0.1" }
tokio = { version = "1", features = ["full"] }
